security:
    encoders:
        Symfony\Component\Security\Core\User\User:
          algorithm: bcrypt
          cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    pedroabp: { password: $2a$04$TGQfHD5azj7.JItDfTRvw.lNUOK3fT05E.eMCVyFCxs7X47WMjNBW, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: login
            anonymous: ~
            # http_basic: ~
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
