<?php


/**
 * Skeleton subclass for performing query and update operations on the 'account' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Oct 24 11:48:20 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AccountPeer extends BaseAccountPeer {
	const ASSETS_ACCOUNT = 0;
	const EQUITY_ACCOUNT = 1;
	const EXPENSES_ACCOUNT = 2;
	const INCOME_ACCOUNT = 3;
	const LIABILITIES_ACCOUNT = 4;

	public static function calculateBalance($debit, $credit, $accountType) {
		switch($accountType) {
			case AccountPeer::ASSETS_ACCOUNT:
			case AccountPeer::EXPENSES_ACCOUNT:
				return $debit - $credit;
				break;
			case AccountPeer::EQUITY_ACCOUNT:
			case AccountPeer::INCOME_ACCOUNT:
			case AccountPeer::LIABILITIES_ACCOUNT:
				return $credit - $debit;
				break;
		};
		return 0;
	}
} // AccountPeer
