<?php


/**
 * Skeleton subclass for representing a row from the 'annuity' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Dec  4 20:22:01 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Annuity extends BaseAnnuity {

} // Annuity
