<?php

/**
 * Skeleton subclass for performing query and update operations on the 'cuenta' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Dec 11 21:16:30 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CuentaPeer extends BaseCuentaPeer {
	const ACTIVO = 0;
	const PATRIMONIO = 1;
	const EGRESO = 2;
	const INGRESO = 3;
	const PASIVO = 4;

	public static function calcularSaldo($debito, $credito, $tipoCuenta) {
		switch($tipoCuenta) {
			case CuentaPeer::ACTIVO :
			case CuentaPeer::EGRESO :
				return $debito - $credito;
				break;
			case CuentaPeer::PATRIMONIO :
			case CuentaPeer::INGRESO :
			case CuentaPeer::PASIVO :
				return $credito - $debito;
				break;
		};
		return 0;
	}

} // CuentaPeer
