<?php


/**
 * Skeleton subclass for representing a row from the 'cuenta' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Dec 11 21:16:30 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Cuenta extends BaseCuenta {

} // Cuenta
