debt:
    path:     /
    defaults: { _controller: "ZahlerBundle:Debt:index" }

debt_show:
    path:     /{id}/show
    defaults: { _controller: "ZahlerBundle:Debt:show" }

debt_new:
    path:     /new
    defaults: { _controller: "ZahlerBundle:Debt:new" }

debt_create:
    path:     /create
    defaults: { _controller: "ZahlerBundle:Debt:create" }
    requirements: { _method: post }

debt_edit:
    path:     /{id}/edit
    defaults: { _controller: "ZahlerBundle:Debt:edit" }

debt_update:
    path:     /update/{id}
    defaults: { _controller: "ZahlerBundle:Debt:update" }
    requirements: { _method: post|put }

debt_delete:
    path:     /{id}/delete
    defaults: { _controller: "ZahlerBundle:Debt:delete" }
    requirements: { _method: post|delete }

debt_retrieve:
    path:     /retrieve
    defaults: { _controller: "ZahlerBundle:Debt:retrieve" }
