zahler_homepage:
    path:     /hello/{name}
    defaults: { _controller: ZahlerBundle:Default:index }

ZahlerBundle_accounttype:
        resource: "@ZahlerBundle/Resources/config/routing/accounttype.yml"
        prefix:   /accounttype

ZahlerBundle_account:
        resource: "@ZahlerBundle/Resources/config/routing/account.yml"
        prefix:   /account

ZahlerBundle_transaction:
        resource: "@ZahlerBundle/Resources/config/routing/transaction.yml"
        prefix:   /transaction
        
ZahlerBundle_customer:
        resource: "@ZahlerBundle/Resources/config/routing/customer.yml"
        prefix:   /customer
        
ZahlerBundle_loan:
        resource: "@ZahlerBundle/Resources/config/routing/loan.yml"
        prefix:   /loan
        
ZahlerBundle_payment:
        resource: "@ZahlerBundle/Resources/config/routing/payment.yml"
        prefix:   /payment
        
root:
    path:     /
    defaults: { _controller: "ZahlerBundle:Transaction:index_js" }

login:
    path:     /login
    defaults: { _controller: "ZahlerBundle:Security:login" }
    
login_check:
    path:     /login_check
    defaults: { _controller: "ZahlerBundle:Security:loginCheck" }

logout:
    path:     /logout
