propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  system_user:
    _attributes: { phpName: User }
    sus_user_name: { type: VARCHAR, size: 20, required: true, unique: true, primaryKey: true }
    sus_password: { type: VARCHAR, size: 40, required: true, unique: true }
  account:
    _attributes: { phpName: Account }
    acc_id: { type: INTEGER, required: true, unique: true, primaryKey: true, autoIncrement: true }
    acc_name: { type: VARCHAR, size: 20, required: true, unique: true }
    acc_type: { type: INTEGER, required: true }
  account_transaction:
    _attributes: { phpName: Transaction }
    atr_id: { type: INTEGER, required: true, unique: true, primaryKey: true, autoIncrement: true }
    atr_date: { type: DATE, required: true }
    atr_reference: { type: VARCHAR, size: 20, required: true }
    atr_description: { type: VARCHAR, size: 255, required: true }
    atr_value: { type: REAL, required: true }
    atr_acc_id_debit: { type: INTEGER, required: true, foreignTable: account, foreignReference: acc_id }
    atr_acc_id_credit: { type: INTEGER, required: true, foreignTable: account, foreignReference: acc_id }
  contact:
    _attributes: { phpName: Contact }
    con_id: { type: INTEGER, required: true, unique: true, primaryKey: true, autoIncrement: true }
    con_first_name: { type: VARCHAR, size: 50, required: true }
    con_last_name: { type: VARCHAR, size: 50 }
    con_email: { type: varchar(320) }
    con_address: { type: VARCHAR, size: 100 }
    con_phone_number: { type: VARCHAR, size: 20 }