propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  system_user:
    _attributes: { phpName: User }
    sus_user_name: { type: VARCHAR, size: 20, required: true, unique: true, primaryKey: true }
    sus_password: { type: VARCHAR, size: 40, required: true, unique: true }
  account:
    _attributes: { phpName: Account }
    acc_id: { type: INTEGER, required: true, unique: true, primaryKey: true, autoIncrement: true }
    acc_name: { type: VARCHAR, size: 20, required: true, unique: true }
    acc_act_id: { type: INTEGER, required: true, foreignTable: account_type, foreignReference: act_id }
    acc_debit: { type: REAL, required: true }
    acc_credit: { type: REAL, required: true }
  account_type:
    _attributes: { phpName: AccountType }
    act_id: { type: INTEGER, required: true, unique: true, primaryKey: true, autoIncrement: true }
    act_name: { type: VARCHAR, size: 20, required: true, unique: true }
  account_transaction:
    _attributes: { phpName: Transaction }
    atr_id: { type: INTEGER, required: true, unique: true, primaryKey: true, autoIncrement: true }
    atr_date: { type: DATE, required: true }
    atr_acc_id_source: { type: INTEGER, required: true, foreignTable: account, foreignReference: acc_id }
    atr_acc_id_target: { type: INTEGER, required: true, foreignTable: account, foreignReference: acc_id }
    atr_value: { type: REAL, required: true }
    atr_reference: { type: VARCHAR, size: 20, required: true }
    atr_description: { type: VARCHAR, size: 255, required: true }
    