propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  usuario:
    _attributes: { phpName: Usuario }
    usu_login: { type: VARCHAR, size: 20, required: true, unique: true, primaryKey: true }
    usu_password: { type: VARCHAR, size: 40, required: true, unique: true }
  cuenta:
    _attributes: { phpName: Cuenta }
    cue_id: { type: INTEGER, required: true, unique: true, primaryKey: true, autoIncrement: true }
    cue_nombre: { type: VARCHAR, size: 20, required: true, unique: true }
    cue_tipo: { type: INTEGER, required: true }
  transaccion:
    _attributes: { phpName: Transaccion }
    tra_id: { type: INTEGER, required: true, unique: true, primaryKey: true, autoIncrement: true }
    tra_fecha: { type: DATE, required: true }
    tra_referencia: { type: VARCHAR, size: 20, required: true }
    tra_descripcion: { type: VARCHAR, size: 255, required: true }
    tra_valor: { type: REAL, required: true }
    tra_cue_id_debito: { type: INTEGER, required: true, foreignTable: cuenta, foreignReference: cue_id }
    tra_cue_id_credito: { type: INTEGER, required: true, foreignTable: cuenta, foreignReference: cue_id }
  contacto:
    _attributes: { phpName: Contacto }
    con_id: { type: INTEGER, required: true, unique: true, primaryKey: true, autoIncrement: true }
    con_nombres: { type: VARCHAR, size: 50, required: true }
    con_apellidos: { type: VARCHAR, size: 50 }
    con_email: { type: varchar(320) }
    con_direccion: { type: VARCHAR, size: 100 }
    con_telefono: { type: VARCHAR, size: 20 }
  prestamo:
    _attributes: { phpName: Prestamo }
    pre_id: { type: INTEGER, required: true, unique: true, primaryKey: true, autoIncrement: true }
    pre_con_id: { type: INTEGER, required: true, foreignTable: contacto, foreignReference: con_id }
    pre_tra_id: { type: INTEGER, required: true, foreignTable: transaccion, foreignReference: tra_id }
    pre_tasa_interes: { type: REAL, required: true }
  pago_prestamo:
    _attributes: { phpName: PagoPrestamo }
    pap_id: { type: INTEGER, required: true, unique: true, primaryKey: true, autoIncrement: true }
    pap_pre_id: { type: INTEGER, required: true, foreignTable: prestamo, foreignReference: pre_id }
    pap_tra_id: { type: INTEGER, required: true, foreignTable: transaccion, foreignReference: tra_id }
